services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:              <--- No se exponen puertos, accesible solo via nginx
    #   - "3002:3002"
    container_name: portfolio-christian
    restart: always
    env_file:
      - .env
    volumes:
      - portfolio-public:/app/public
    networks:
      - red-internet

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    # ports:              <--- No se exponen puertos, accesible solo via nginx
    #   - "5000:5000"
    container_name: portfolio-api
    restart: always
    env_file:
      - ./api/.env
    environment:
      - PUBLIC_DIR=/app/public
    volumes:
      - portfolio-public:/app/public
    depends_on:
      - mongo
    networks:
      - red-internet

  mongo:
    image: mongo:7
    container_name: portfolio-mongo
    restart: always
    volumes:
      - portfolio-mongo-data:/data/db
    # No se exponen puertos, solo accesible internamente
    networks:
      - red-internet

volumes:
  portfolio-public:
  portfolio-mongo-data:

networks:
  red-internet:
    external: true