services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:              <--- We don't use ports anymore for security reasons, the app is only accessible through nginx
    #   - "3002:3002"
    container_name: portfolio-christian  # <--- Container name for easier management
    restart: always
    env_file:
      - .env
    networks:
      - red-internet      # <--- Connect to the external network for internet access

networks:
  red-internet:
    external: true